version: '2'

services:
  janus:
    build:
      context: .
      dockerfile: janus.dockerfile
    volumes:
      - ./janus-testserver-config/:/opt/janus/etc/janus/
      - ./keys:/opt/keys/
    
networks:
  default:
    external:
      name: sdnet
