version: '2'

services:
  janus:
    #image: atyenoria/janus-webrtc-gateway-docker:latest
    # image: mcroth/docker-janus:latest 
    build:
      context: .
      dockerfile: janus.dockerfile
    container_name: janus-new
    volumes:
      - ./janus/etc/janus/:/opt/janus/etc/janus/
      - ./keys:/opt/keys/
      - ./janus/janus.log:/var/log/janus.log:rw
    ports:
      - 8088:8088
      - 8081:8081
      - 8188:8188

  http-server:
    image: alfg/nginx-rtmp
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./http:/www/static:ro
      - ./mime.types:/etc/nginx/mime.types
      - ./keys:/opt/certs

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
